<?php ($representatives = $payload['collections']['representatives']); ?>
<section class="page-heading compact-heading">
    <div><p class="eyebrow">UNDERSTAND / PREDICTIVE ANALYTICS</p><h1>See what’s next.</h1><p class="page-subtitle">Signals from visit history help the team prioritize the next best field action.</p></div>
    <div class="period-switcher"><button class="active">7 days</button><button>30 days</button><button>Quarter</button></div>
</section>
<section class="analytics-grid">
    <article class="panel chart-panel"><div class="panel-header"><div><p class="eyebrow">ENGAGEMENT TREND</p><h2>Visits & doctor engagement</h2></div><span class="chart-legend"><i></i>Completed visits</span></div><div class="line-chart"><div class="chart-y"><span>24</span><span>18</span><span>12</span><span>6</span><span>0</span></div><div class="chart-area"><div class="chart-grid-lines"><i></i><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 620 220" preserveAspectRatio="none" aria-label="Visit trend chart"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#6d5dfc" stop-opacity=".28"/><stop offset="100%" stop-color="#6d5dfc" stop-opacity="0"/></linearGradient></defs><path d="M0,170 C45,160 68,126 105,138 S160,164 205,113 S255,116 295,82 S350,106 387,75 S430,89 472,51 S530,85 570,42 S600,46 620,28 L620,220 L0,220 Z" fill="url(#fill)"/><path d="M0,170 C45,160 68,126 105,138 S160,164 205,113 S255,116 295,82 S350,106 387,75 S430,89 472,51 S530,85 570,42 S600,46 620,28" fill="none" stroke="#6d5dfc" stroke-width="3"/></svg><div class="chart-x"><span>Sep 17</span><span>Sep 18</span><span>Sep 19</span><span>Sep 20</span><span>Sep 21</span><span>Sep 22</span><span>Sep 23</span></div></div></div></article>
    <article class="panel insight-panel"><div class="panel-header"><div><p class="eyebrow">RECOMMENDATION ENGINE</p><h2>Priority signals</h2></div><span class="signal-icon">✦</span></div><div class="signal-item"><span class="signal-rank">01</span><div><strong>Revisit Asian Hospital</strong><p>Engagement is down 22% this week. Schedule a priority visit for the next 48 hours.</p></div><span class="signal-arrow">→</span></div><div class="signal-item"><span class="signal-rank">02</span><div><strong>Expand Makati Central</strong><p>Coverage is strong, but 6 doctors have not been visited in 14 days.</p></div><span class="signal-arrow">→</span></div><div class="signal-item"><span class="signal-rank">03</span><div><strong>Restock conversation</strong><p>Cefuroxime demand is rising at two facilities. Pair the alert with the next visit.</p></div><span class="signal-arrow">→</span></div></article>
</section>
<section class="panel performance-panel"><div class="panel-header"><div><p class="eyebrow">PERFORMANCE OUTLOOK</p><h2>Representative coverage</h2></div><a href="<?php echo e(route('representatives')); ?>" class="text-link">Open team view <span>→</span></a></div><div class="performance-list"><?php $__currentLoopData = $representatives; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $rep): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="performance-row"><div class="table-person"><div class="avatar avatar-<?php echo e($loop->index + 1); ?>"><?php echo e(strtoupper(substr($rep['name'] ?? 'R', 0, 1))); ?></div><div><strong><?php echo e($rep['name']); ?></strong><small><?php echo e($rep['territory'] ?? '—'); ?></small></div></div><div class="performance-bar"><span style="width: <?php echo e($rep['coverage'] ?? 0); ?>%"></span></div><strong><?php echo e($rep['coverage'] ?? 0); ?>%</strong><span class="trend-up">↑ <?php echo e(3 + $loop->index); ?>%</span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section><?php /**PATH C:\Capstone\Preventia-Field-Monitoring\preventia-laravel\resources\views/dashboard/sections/analytics.blade.php ENDPATH**/ ?>